services:
  vehicle-scrapping-db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - '5432:5432'
  pg-admin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - '8888:80'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    env_file:
      - .env

volumes:
  pgadmin-data:

  # vehicle_scrapping_api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - '8000:8000'
  #   depends_on:
  #     - vehicle-scrapping-db
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./src:/usr/src/app/src
